AWSTemplateFormatVersion: '2019-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API de Envios

Resources:
  Envios:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Timeout: 30
      Events:
        GetEnvio:
          Type: Api
          Properties:
            Path: /envios/{idEnvio}
            Method: get
        EnviosPendientes:
          Type: Api
          Properties:
            Path: /envios/pendientes
            Method: get
        CrearEnvio:
          Type: Api
          Properties:
            Path: /envios
            Method: post
        CrearMovimiento:
          Type: Api
          Properties:
            Path: /envios/{idEnvio}/movimiento
            Method: post
        Entregado:
          Type: Api
          Properties:
            Path: /envios/{idEnvio}/entregado
            Method: post
